"""Prepare joint intent + DST training data for TherapistTransformer.

~50 examples per class → ~650 total → ~552 train / 98 val.
"""
from __future__ import annotations

import json
import random
import re
from pathlib import Path

SEED_DATA: list[dict] = [
    # ── crisis ──────────────────────────────────────────────────────────────
    {"text": "I've been thinking about hurting myself",                     "intent": "crisis"},
    {"text": "I don't want to be here anymore",                             "intent": "crisis"},
    {"text": "I've been having thoughts of suicide",                        "intent": "crisis"},
    {"text": "I've been cutting myself again",                              "intent": "crisis"},
    {"text": "I want to end it all",                                        "intent": "crisis"},
    {"text": "I keep thinking about not waking up",                         "intent": "crisis"},
    {"text": "I feel like disappearing forever",                            "intent": "crisis"},
    {"text": "I've been hurting myself to cope",                            "intent": "crisis"},
    {"text": "Nobody would miss me if I was gone",                          "intent": "crisis"},
    {"text": "I planned how I would do it",                                 "intent": "crisis"},
    {"text": "I took too many pills last night",                            "intent": "crisis"},
    {"text": "I feel like everyone would be better without me",             "intent": "crisis"},
    {"text": "I can't see a reason to keep going",                          "intent": "crisis"},
    {"text": "I've been writing goodbye notes",                             "intent": "crisis"},
    {"text": "The pain is unbearable I just want it to stop",               "intent": "crisis"},
    {"text": "I have a plan to kill myself",                                "intent": "crisis"},
    {"text": "I scratched my arms until they bled",                         "intent": "crisis"},
    {"text": "I feel completely hopeless and want to die",                  "intent": "crisis"},
    {"text": "I'm scared of what I might do to myself tonight",             "intent": "crisis"},
    {"text": "Life feels not worth living anymore",                         "intent": "crisis"},
    {"text": "I've been giving away my things",                             "intent": "crisis"},
    {"text": "I stood at the edge of the bridge for a long time",           "intent": "crisis"},
    {"text": "I can't stop thinking about suicide",                         "intent": "crisis"},
    {"text": "I burned myself again",                                       "intent": "crisis"},
    {"text": "I really don't want to be alive",                             "intent": "crisis"},
    {"text": "I've been thinking about overdosing",                         "intent": "crisis"},
    {"text": "I feel like there is no way out except ending it",            "intent": "crisis"},
    {"text": "I keep imagining what it would be like if I wasn't here",     "intent": "crisis"},
    {"text": "I told someone I was fine but I'm not I want to die",         "intent": "crisis"},
    {"text": "I feel like the world would be better without me in it",      "intent": "crisis"},
    {"text": "I'm at the point where I think ending my life is the answer", "intent": "crisis"},
    {"text": "I can't do this anymore I want out",                          "intent": "crisis"},
    {"text": "I starve myself to punish myself",                            "intent": "crisis"},
    {"text": "I have been thinking about self harm all day",                "intent": "crisis"},
    {"text": "I've been secretly hurting myself for months",                "intent": "crisis"},
    {"text": "I'm scared I'll act on these thoughts tonight",               "intent": "crisis"},
    {"text": "I think about jumping from a high place",                     "intent": "crisis"},
    {"text": "I've already said goodbye to people in my head",              "intent": "crisis"},
    {"text": "I feel no hope at all and I want to die",                     "intent": "crisis"},
    {"text": "I started carrying something to hurt myself with",            "intent": "crisis"},
    {"text": "I've been researching methods",                               "intent": "crisis"},
    {"text": "I don't see the point of staying alive",                      "intent": "crisis"},
    {"text": "Everything is too much and I want it to end",                 "intent": "crisis"},
    {"text": "I feel like dying is the only escape",                        "intent": "crisis"},
    {"text": "I've told no one but I'm not safe right now",                 "intent": "crisis"},
    {"text": "I've been making cuts on my thighs",                         "intent": "crisis"},
    {"text": "I feel nothing and part of me wants to not exist",            "intent": "crisis"},
    {"text": "I wrote a note last night",                                   "intent": "crisis"},
    {"text": "I'm thinking about hurting myself when I get home",           "intent": "crisis"},
    {"text": "The thoughts are getting louder and more specific",           "intent": "crisis"},

    # ── anxiety ─────────────────────────────────────────────────────────────
    {"text": "I can't stop worrying about everything",                      "intent": "anxiety"},
    {"text": "I had a panic attack on the tube this morning",               "intent": "anxiety"},
    {"text": "My heart races every time I think about it",                  "intent": "anxiety"},
    {"text": "I feel overwhelmed all the time",                             "intent": "anxiety"},
    {"text": "I keep catastrophising about the future",                     "intent": "anxiety"},
    {"text": "I feel so anxious and I can't breathe",                       "intent": "anxiety"},
    {"text": "I get dizzy and shaky when I'm stressed",                     "intent": "anxiety"},
    {"text": "My mind won't stop racing at night",                          "intent": "anxiety"},
    {"text": "I feel nervous for no reason all the time",                   "intent": "anxiety"},
    {"text": "I avoid going outside because of my anxiety",                 "intent": "anxiety"},
    {"text": "I'm terrified of making mistakes at work",                    "intent": "anxiety"},
    {"text": "I had a panic attack in the middle of class",                 "intent": "anxiety"},
    {"text": "I worry constantly that something bad will happen",           "intent": "anxiety"},
    {"text": "Even small decisions make me incredibly anxious",             "intent": "anxiety"},
    {"text": "I feel like something awful is about to happen",              "intent": "anxiety"},
    {"text": "My hands shake when I'm in social situations",                "intent": "anxiety"},
    {"text": "I can't sleep because my brain won't stop",                   "intent": "anxiety"},
    {"text": "I feel a tight knot in my chest constantly",                  "intent": "anxiety"},
    {"text": "I'm scared to leave the house some days",                     "intent": "anxiety"},
    {"text": "The dread I feel every morning is exhausting",                "intent": "anxiety"},
    {"text": "I overthink every conversation I have",                       "intent": "anxiety"},
    {"text": "I've been having really bad health anxiety",                  "intent": "anxiety"},
    {"text": "I cancelled plans again because of my nerves",                "intent": "anxiety"},
    {"text": "I feel paralysed by all my worries",                          "intent": "anxiety"},
    {"text": "I can feel my anxiety getting worse",                         "intent": "anxiety"},
    {"text": "I feel like I'm constantly on edge about nothing specific",   "intent": "anxiety"},
    {"text": "My anxiety makes it hard to be around people",                "intent": "anxiety"},
    {"text": "I woke up at 3am panicking about things I can't control",     "intent": "anxiety"},
    {"text": "I keep imagining worst case scenarios for everything",        "intent": "anxiety"},
    {"text": "I feel tense in my body all day long",                        "intent": "anxiety"},
    {"text": "I had to leave a social event because I felt so panicked",    "intent": "anxiety"},
    {"text": "I am terrified of what people think of me",                   "intent": "anxiety"},
    {"text": "I feel breathless when I think about the future",             "intent": "anxiety"},
    {"text": "I have been avoiding phone calls because they make me panic", "intent": "anxiety"},
    {"text": "My anxiety has been out of control lately",                   "intent": "anxiety"},
    {"text": "I feel like I'm always waiting for something bad to happen",  "intent": "anxiety"},
    {"text": "Even resting doesn't calm my nervous system down",            "intent": "anxiety"},
    {"text": "I spiral into panic every time I make a small mistake",       "intent": "anxiety"},
    {"text": "I can't focus because the worry is constant",                 "intent": "anxiety"},
    {"text": "I feel anxious even when there is nothing to worry about",    "intent": "anxiety"},
    {"text": "My stomach is in knots every single morning",                 "intent": "anxiety"},
    {"text": "I've started avoiding situations that might trigger panic",   "intent": "anxiety"},
    {"text": "I'm scared of my own anxiety",                                "intent": "anxiety"},
    {"text": "I went to A&E thinking I was having a heart attack but it was panic", "intent": "anxiety"},
    {"text": "I feel on edge every single day",                             "intent": "anxiety"},
    {"text": "My heart pounds when I open emails",                          "intent": "anxiety"},
    {"text": "The anticipatory anxiety is sometimes worse than the thing itself", "intent": "anxiety"},
    {"text": "I barely leave my room because everything feels threatening", "intent": "anxiety"},
    {"text": "I feel a wave of dread when I wake up every morning",         "intent": "anxiety"},
    {"text": "I can't enjoy anything because I'm always waiting for it to go wrong", "intent": "anxiety"},

    # ── depression ──────────────────────────────────────────────────────────
    {"text": "I just feel empty like nothing matters",                      "intent": "depression"},
    {"text": "I can't get out of bed most mornings",                        "intent": "depression"},
    {"text": "Everything feels pointless",                                  "intent": "depression"},
    {"text": "I've lost interest in things I used to love",                 "intent": "depression"},
    {"text": "I feel hopeless and numb",                                    "intent": "depression"},
    {"text": "I'm exhausted all the time for no reason",                    "intent": "depression"},
    {"text": "I don't feel anything anymore",                               "intent": "depression"},
    {"text": "Getting through the day feels impossible",                    "intent": "depression"},
    {"text": "I haven't showered or eaten properly in days",                "intent": "depression"},
    {"text": "I feel like a burden to everyone around me",                  "intent": "depression"},
    {"text": "There's this heavy darkness I can't shake",                   "intent": "depression"},
    {"text": "I stopped enjoying the things I used to love",                "intent": "depression"},
    {"text": "I feel completely disconnected from everything",              "intent": "depression"},
    {"text": "I cry for no reason most days",                               "intent": "depression"},
    {"text": "I feel like I'm just going through the motions",              "intent": "depression"},
    {"text": "I don't see the point in anything anymore",                   "intent": "depression"},
    {"text": "I've been isolating myself from everyone",                    "intent": "depression"},
    {"text": "My depression has been really bad lately",                    "intent": "depression"},
    {"text": "I feel worthless and I don't know why",                       "intent": "depression"},
    {"text": "I can't concentrate on anything",                             "intent": "depression"},
    {"text": "I feel like nothing will ever get better",                    "intent": "depression"},
    {"text": "I just want to sleep and not wake up for a while",            "intent": "depression"},
    {"text": "I don't recognise myself anymore",                            "intent": "depression"},
    {"text": "The sadness won't go away no matter what I do",               "intent": "depression"},
    {"text": "I feel so low today I could barely move",                     "intent": "depression"},
    {"text": "I've stopped replying to messages because I don't have energy","intent": "depression"},
    {"text": "Everything takes enormous effort including getting dressed",   "intent": "depression"},
    {"text": "I stare at the ceiling for hours unable to move",             "intent": "depression"},
    {"text": "The world looks grey and flat all the time now",              "intent": "depression"},
    {"text": "I feel like I'm wading through mud every single day",         "intent": "depression"},
    {"text": "I haven't laughed in so long I've forgotten what it feels like","intent": "depression"},
    {"text": "I've been cancelling on everyone because I can't face people","intent": "depression"},
    {"text": "There is a weight on my chest that never lifts",              "intent": "depression"},
    {"text": "I feel completely hollow inside",                             "intent": "depression"},
    {"text": "I don't care about anything and that scares me",              "intent": "depression"},
    {"text": "My appetite has disappeared completely",                      "intent": "depression"},
    {"text": "I feel detached from my own life",                            "intent": "depression"},
    {"text": "I've been in bed all weekend and I hate myself for it",       "intent": "depression"},
    {"text": "I keep waking up hoping the sadness will be gone but it never is","intent": "depression"},
    {"text": "I have no motivation at all",                                 "intent": "depression"},
    {"text": "I feel like the colour has drained out of everything",        "intent": "depression"},
    {"text": "I barely exist lately I just go through the motions",         "intent": "depression"},
    {"text": "I used to love music but now it doesn't move me",             "intent": "depression"},
    {"text": "I feel sad all the time without any obvious reason",          "intent": "depression"},
    {"text": "I haven't left the house in days and I don't care",           "intent": "depression"},
    {"text": "I am exhausted by being alive",                               "intent": "depression"},
    {"text": "I feel permanently tired no matter how much I sleep",         "intent": "depression"},
    {"text": "There's nothing I'm looking forward to",                      "intent": "depression"},
    {"text": "I feel like I'm disappearing",                                "intent": "depression"},
    {"text": "I've been numb for so long I've forgotten what feeling normal is","intent": "depression"},

    # ── venting ─────────────────────────────────────────────────────────────
    {"text": "I'm so sick of how my flatmate treats me",                    "intent": "venting"},
    {"text": "I just need to vent today was terrible",                      "intent": "venting"},
    {"text": "I'm fed up with everything",                                  "intent": "venting"},
    {"text": "I'm so pissed off right now",                                 "intent": "venting"},
    {"text": "I can't stand this anymore",                                  "intent": "venting"},
    {"text": "Everything went wrong today and I'm so angry",               "intent": "venting"},
    {"text": "Nobody listens to me and it's driving me mad",                "intent": "venting"},
    {"text": "I'm so frustrated I could scream",                            "intent": "venting"},
    {"text": "Today was an absolute disaster from start to finish",         "intent": "venting"},
    {"text": "I hate everything about my situation right now",              "intent": "venting"},
    {"text": "I just need to get this off my chest",                        "intent": "venting"},
    {"text": "I'm beyond exhausted with all of it",                         "intent": "venting"},
    {"text": "I snapped at someone today and I feel awful",                 "intent": "venting"},
    {"text": "Nothing is going right and I'm so angry",                     "intent": "venting"},
    {"text": "I'm sick and tired of being taken for granted",               "intent": "venting"},
    {"text": "I missed my bus and everything after just fell apart",        "intent": "venting"},
    {"text": "I had the worst commute and I'm still fuming",                "intent": "venting"},
    {"text": "I'm annoyed and I just need someone to hear me",              "intent": "venting"},
    {"text": "I kept getting interrupted in every meeting today",           "intent": "venting"},
    {"text": "Everyone ignored my ideas again and I'm livid",               "intent": "venting"},
    {"text": "I got soaked in the rain and missed my train",                "intent": "venting"},
    {"text": "I got blamed for something that wasn't my fault",             "intent": "venting"},
    {"text": "I'm just really frustrated today",                            "intent": "venting"},
    {"text": "I need to vent I am so angry right now",                      "intent": "venting"},
    {"text": "The day started badly and got worse",                         "intent": "venting"},
    {"text": "I'm absolutely seething about what happened",                 "intent": "venting"},
    {"text": "People are so inconsiderate and it makes me furious",         "intent": "venting"},
    {"text": "I feel like I'm always the one who gives and never receives", "intent": "venting"},
    {"text": "I'm so done with people treating me like I don't matter",     "intent": "venting"},
    {"text": "I lost my temper today and now I feel terrible about it",     "intent": "venting"},
    {"text": "I've had enough I'm so done",                                 "intent": "venting"},
    {"text": "I'm furious at something that happened today",                "intent": "venting"},
    {"text": "I want to scream into a pillow",                              "intent": "venting"},
    {"text": "Everything is winding me up today",                           "intent": "venting"},
    {"text": "I feel like I'm constantly being disrespected",               "intent": "venting"},
    {"text": "Someone completely dismissed what I said and I'm still angry","intent": "venting"},
    {"text": "I feel disrespected and underappreciated",                    "intent": "venting"},
    {"text": "I need to rant because I have nowhere else to put this",      "intent": "venting"},
    {"text": "I keep swallowing my anger and today I couldn't anymore",     "intent": "venting"},
    {"text": "I am so fed up I just need someone to listen",                "intent": "venting"},
    {"text": "My day was awful and I just need to talk about it",           "intent": "venting"},
    {"text": "I got into an argument and I'm still shaking",                "intent": "venting"},
    {"text": "I feel so dismissed and I'm furious",                         "intent": "venting"},
    {"text": "Today tested every bit of my patience",                       "intent": "venting"},
    {"text": "I feel so wound up right now",                                "intent": "venting"},
    {"text": "I'm raging about something that happened and need to let it out","intent": "venting"},
    {"text": "I can't believe how rude people can be",                      "intent": "venting"},
    {"text": "I just had a really bad day and I'm still in a terrible mood","intent": "venting"},
    {"text": "I feel like I always have to be the bigger person and I'm sick of it","intent": "venting"},
    {"text": "I want to vent about what just happened",                     "intent": "venting"},

    # ── seeking_advice ──────────────────────────────────────────────────────
    {"text": "I don't know what to do about my relationship",               "intent": "seeking_advice"},
    {"text": "Should I quit my job",                                        "intent": "seeking_advice"},
    {"text": "What do you think I should do",                               "intent": "seeking_advice"},
    {"text": "How do I deal with this",                                     "intent": "seeking_advice"},
    {"text": "Any advice on how to handle this",                            "intent": "seeking_advice"},
    {"text": "I'm not sure whether to confront them or let it go",          "intent": "seeking_advice"},
    {"text": "What would you do if you were in my position",                "intent": "seeking_advice"},
    {"text": "I need help figuring out what to do next",                    "intent": "seeking_advice"},
    {"text": "Should I tell them how I feel",                               "intent": "seeking_advice"},
    {"text": "I need some guidance on this situation",                      "intent": "seeking_advice"},
    {"text": "Can you help me think through this decision",                 "intent": "seeking_advice"},
    {"text": "I have no idea how to approach this",                         "intent": "seeking_advice"},
    {"text": "What's the right thing to do here",                           "intent": "seeking_advice"},
    {"text": "I'm torn between two options and don't know which to choose", "intent": "seeking_advice"},
    {"text": "How do I tell my parents about this",                         "intent": "seeking_advice"},
    {"text": "Is it okay to set boundaries with family",                    "intent": "seeking_advice"},
    {"text": "What should I say to my partner about this",                  "intent": "seeking_advice"},
    {"text": "I need advice on how to stop procrastinating",                "intent": "seeking_advice"},
    {"text": "How can I stop feeling guilty all the time",                  "intent": "seeking_advice"},
    {"text": "Should I see a therapist or try to manage alone",             "intent": "seeking_advice"},
    {"text": "How do I stop comparing myself to everyone",                  "intent": "seeking_advice"},
    {"text": "What do I do when I feel like giving up",                     "intent": "seeking_advice"},
    {"text": "How do I start setting boundaries",                           "intent": "seeking_advice"},
    {"text": "I want to get better but don't know how",                     "intent": "seeking_advice"},
    {"text": "What steps can I take to manage my anxiety",                  "intent": "seeking_advice"},
    {"text": "I don't know how to talk to someone I've hurt",               "intent": "seeking_advice"},
    {"text": "How do I forgive someone who hurt me",                        "intent": "seeking_advice"},
    {"text": "I need help deciding whether to end this friendship",         "intent": "seeking_advice"},
    {"text": "How do I stop self-sabotaging",                               "intent": "seeking_advice"},
    {"text": "I don't know whether to reach out or give them space",        "intent": "seeking_advice"},
    {"text": "What should I do when I feel completely stuck",               "intent": "seeking_advice"},
    {"text": "Is it normal to feel like this",                              "intent": "seeking_advice"},
    {"text": "How do I handle someone who keeps triggering me",             "intent": "seeking_advice"},
    {"text": "How can I be kinder to myself",                               "intent": "seeking_advice"},
    {"text": "What do I do when nothing seems to help",                     "intent": "seeking_advice"},
    {"text": "Can you give me some coping strategies",                      "intent": "seeking_advice"},
    {"text": "How do I stop letting fear control my decisions",             "intent": "seeking_advice"},
    {"text": "I need advice I don't know who else to ask",                  "intent": "seeking_advice"},
    {"text": "What would help me feel less overwhelmed",                    "intent": "seeking_advice"},
    {"text": "How do I rebuild my confidence after a setback",              "intent": "seeking_advice"},
    {"text": "Do you think I'm making a mistake",                           "intent": "seeking_advice"},
    {"text": "I want to change but I don't know where to start",            "intent": "seeking_advice"},
    {"text": "How do I break a bad habit",                                  "intent": "seeking_advice"},
    {"text": "Should I apologise even though it wasn't really my fault",    "intent": "seeking_advice"},
    {"text": "How can I stop being so hard on myself",                      "intent": "seeking_advice"},
    {"text": "I need some perspective on this situation",                   "intent": "seeking_advice"},
    {"text": "What do you think would help me most right now",              "intent": "seeking_advice"},
    {"text": "How do I deal with someone who never takes responsibility",   "intent": "seeking_advice"},
    {"text": "I'm looking for guidance not judgement",                      "intent": "seeking_advice"},
    {"text": "What are some things that might help when I feel this low",   "intent": "seeking_advice"},

    # ── relationship ────────────────────────────────────────────────────────
    {"text": "My partner and I keep having the same argument",              "intent": "relationship"},
    {"text": "I feel so lonely even when I'm with people",                  "intent": "relationship"},
    {"text": "My mum doesn't understand me at all",                         "intent": "relationship"},
    {"text": "I had a huge fight with my boyfriend",                        "intent": "relationship"},
    {"text": "My friend betrayed my trust",                                 "intent": "relationship"},
    {"text": "I feel disconnected from my family",                          "intent": "relationship"},
    {"text": "My girlfriend and I haven't been getting along",              "intent": "relationship"},
    {"text": "I feel invisible in my friendships",                          "intent": "relationship"},
    {"text": "My dad said something that really hurt me",                   "intent": "relationship"},
    {"text": "I don't feel close to anyone anymore",                        "intent": "relationship"},
    {"text": "My best friend and I had a falling out",                      "intent": "relationship"},
    {"text": "I feel like my partner doesn't appreciate me",                "intent": "relationship"},
    {"text": "My sister keeps criticising everything I do",                 "intent": "relationship"},
    {"text": "I feel completely alone even surrounded by people",           "intent": "relationship"},
    {"text": "My parents don't support my choices",                         "intent": "relationship"},
    {"text": "My relationship feels one sided",                             "intent": "relationship"},
    {"text": "I push people away and I don't know why",                     "intent": "relationship"},
    {"text": "I'm scared of being abandoned",                               "intent": "relationship"},
    {"text": "I miss the closeness we used to have",                        "intent": "relationship"},
    {"text": "I don't have anyone I can really talk to",                    "intent": "relationship"},
    {"text": "My family doesn't know about my mental health",               "intent": "relationship"},
    {"text": "I feel like a burden to the people I love",                   "intent": "relationship"},
    {"text": "My partner doesn't take my emotions seriously",               "intent": "relationship"},
    {"text": "I struggle to trust people after being hurt",                 "intent": "relationship"},
    {"text": "I've been feeling really lonely lately",                      "intent": "relationship"},
    {"text": "My boyfriend and I broke up and I'm devastated",              "intent": "relationship"},
    {"text": "I feel like no one actually knows the real me",               "intent": "relationship"},
    {"text": "I feel unwanted in my friendships",                           "intent": "relationship"},
    {"text": "My family is toxic but I don't know how to distance myself",  "intent": "relationship"},
    {"text": "I gave everything to this relationship and they left",        "intent": "relationship"},
    {"text": "I have no one to call when things get hard",                  "intent": "relationship"},
    {"text": "I always end up alone in the end",                            "intent": "relationship"},
    {"text": "My partner cheated and I don't know what to do",              "intent": "relationship"},
    {"text": "I feel used by people who call themselves my friends",        "intent": "relationship"},
    {"text": "My mum makes me feel guilty for having my own life",          "intent": "relationship"},
    {"text": "I've been ghosted by someone I really cared about",           "intent": "relationship"},
    {"text": "People keep leaving me and I don't understand why",           "intent": "relationship"},
    {"text": "I feel like I care more about people than they care about me","intent": "relationship"},
    {"text": "My dad has never really been there for me",                   "intent": "relationship"},
    {"text": "I feel isolated and like nobody gets me",                     "intent": "relationship"},
    {"text": "My partner and I communicate terribly",                       "intent": "relationship"},
    {"text": "I don't know how to be close to people without getting hurt", "intent": "relationship"},
    {"text": "I grew up in a home where emotions weren't talked about",     "intent": "relationship"},
    {"text": "I feel like I attract people who take advantage of me",       "intent": "relationship"},
    {"text": "I've been distancing myself from my friends and I don't know why","intent": "relationship"},
    {"text": "My relationship with my mother is complicated and painful",   "intent": "relationship"},
    {"text": "I feel like I can't lean on anyone",                          "intent": "relationship"},
    {"text": "My brother and I haven't spoken in months",                   "intent": "relationship"},
    {"text": "I lost my best friend and I'm grieving that",                 "intent": "relationship"},
    {"text": "I feel safer alone than with people",                         "intent": "relationship"},

    # ── work_stress ─────────────────────────────────────────────────────────
    {"text": "I have three deadlines this week and I can't cope",           "intent": "work_stress"},
    {"text": "I think I'm burning out from work",                           "intent": "work_stress"},
    {"text": "My exams are in two weeks and I'm not ready",                 "intent": "work_stress"},
    {"text": "My boss keeps piling on work",                                "intent": "work_stress"},
    {"text": "I stayed at the office until midnight again",                 "intent": "work_stress"},
    {"text": "I'm dreading going into work tomorrow",                       "intent": "work_stress"},
    {"text": "I haven't had a day off in three weeks",                      "intent": "work_stress"},
    {"text": "My workload is completely unmanageable",                      "intent": "work_stress"},
    {"text": "I got a bad performance review and I'm devastated",           "intent": "work_stress"},
    {"text": "I'm terrified of failing my dissertation",                    "intent": "work_stress"},
    {"text": "I feel like I'm always behind at work",                       "intent": "work_stress"},
    {"text": "I got shouted at by my manager in front of everyone",         "intent": "work_stress"},
    {"text": "University is overwhelming me",                               "intent": "work_stress"},
    {"text": "I feel like I'm going to get fired",                          "intent": "work_stress"},
    {"text": "I missed a deadline and I feel terrible",                     "intent": "work_stress"},
    {"text": "I work from home and I can't switch off",                     "intent": "work_stress"},
    {"text": "I'm struggling to keep up with my studies",                   "intent": "work_stress"},
    {"text": "I feel like a failure at my job",                             "intent": "work_stress"},
    {"text": "I was passed over for promotion again",                       "intent": "work_stress"},
    {"text": "I'm stressed about money because work is slow",               "intent": "work_stress"},
    {"text": "I have an important presentation tomorrow and I'm terrified", "intent": "work_stress"},
    {"text": "I got made redundant and I don't know what to do",            "intent": "work_stress"},
    {"text": "I'm struggling to balance uni and a part time job",           "intent": "work_stress"},
    {"text": "I feel completely underwater at work",                        "intent": "work_stress"},
    {"text": "My boss makes impossible demands and I can't keep up",        "intent": "work_stress"},
    {"text": "I'm exhausted from work and I have no time for myself",       "intent": "work_stress"},
    {"text": "The pressure at work is crushing me",                         "intent": "work_stress"},
    {"text": "I failed an exam and I feel like such a failure",             "intent": "work_stress"},
    {"text": "I work twelve hour days and I'm running on empty",            "intent": "work_stress"},
    {"text": "My job is making me physically ill from stress",              "intent": "work_stress"},
    {"text": "I'm scared I won't pass my degree",                           "intent": "work_stress"},
    {"text": "I can't keep up with the pace at my new job",                 "intent": "work_stress"},
    {"text": "I've been working evenings and weekends for months",          "intent": "work_stress"},
    {"text": "My manager micromanages everything and it's making me a wreck","intent": "work_stress"},
    {"text": "I'm behind on coursework and the deadline is tomorrow",       "intent": "work_stress"},
    {"text": "I dread Sunday evenings because Monday means work",           "intent": "work_stress"},
    {"text": "I feel trapped in a job I hate but I need the money",         "intent": "work_stress"},
    {"text": "I'm losing confidence at work because nothing I do is right","intent": "work_stress"},
    {"text": "My job is destroying my mental health",                       "intent": "work_stress"},
    {"text": "I have so much studying to do and I don't know where to start","intent": "work_stress"},
    {"text": "I'm struggling with my dissertation and time is running out", "intent": "work_stress"},
    {"text": "I keep getting criticised by my team lead and I'm demoralized","intent": "work_stress"},
    {"text": "I've been on edge about a big work project for weeks",        "intent": "work_stress"},
    {"text": "I'm at breaking point with my workload",                      "intent": "work_stress"},
    {"text": "I feel like I'm not cut out for this job",                    "intent": "work_stress"},
    {"text": "There is so much pressure on me at university right now",     "intent": "work_stress"},
    {"text": "I feel like I'm failing at everything career-related",        "intent": "work_stress"},
    {"text": "My career is going nowhere and I feel stuck",                 "intent": "work_stress"},
    {"text": "I worked all weekend and my boss didn't even say thank you",  "intent": "work_stress"},
    {"text": "I'm burning out and I don't know how to stop",                "intent": "work_stress"},

    # ── self_esteem ─────────────────────────────────────────────────────────
    {"text": "I hate how I look",                                           "intent": "self_esteem"},
    {"text": "I'm not smart enough for this",                               "intent": "self_esteem"},
    {"text": "Everyone else seems to have their life together",             "intent": "self_esteem"},
    {"text": "I feel like I'm not good enough",                             "intent": "self_esteem"},
    {"text": "I keep comparing myself to others",                           "intent": "self_esteem"},
    {"text": "I don't think I deserve to be happy",                         "intent": "self_esteem"},
    {"text": "I feel ugly and worthless",                                   "intent": "self_esteem"},
    {"text": "I'm embarrassed by who I am",                                 "intent": "self_esteem"},
    {"text": "I feel stupid compared to everyone around me",                "intent": "self_esteem"},
    {"text": "I can never do anything right",                               "intent": "self_esteem"},
    {"text": "I'm my own worst critic",                                     "intent": "self_esteem"},
    {"text": "I hate myself sometimes",                                     "intent": "self_esteem"},
    {"text": "I feel like a fraud and people will find out",                "intent": "self_esteem"},
    {"text": "I look in the mirror and feel disgusted",                     "intent": "self_esteem"},
    {"text": "I'm not as successful as I should be at my age",              "intent": "self_esteem"},
    {"text": "I don't think I'm likeable",                                  "intent": "self_esteem"},
    {"text": "I feel ashamed of my past",                                   "intent": "self_esteem"},
    {"text": "I can't accept compliments",                                  "intent": "self_esteem"},
    {"text": "I feel inferior to everyone",                                 "intent": "self_esteem"},
    {"text": "I put myself down constantly",                                "intent": "self_esteem"},
    {"text": "I'm terrified of being judged",                               "intent": "self_esteem"},
    {"text": "I feel unlovable",                                            "intent": "self_esteem"},
    {"text": "I never feel like I'm enough",                                "intent": "self_esteem"},
    {"text": "I feel so insecure all the time",                             "intent": "self_esteem"},
    {"text": "I'm scared of failing so I don't even try",                   "intent": "self_esteem"},
    {"text": "I feel like everyone is more capable than me",                "intent": "self_esteem"},
    {"text": "I always assume people secretly dislike me",                  "intent": "self_esteem"},
    {"text": "I minimise my achievements because I feel they don't count",  "intent": "self_esteem"},
    {"text": "I feel like I have to earn my place in every room",           "intent": "self_esteem"},
    {"text": "I feel fundamentally broken compared to other people",        "intent": "self_esteem"},
    {"text": "I don't think I'm worthy of love",                            "intent": "self_esteem"},
    {"text": "I constantly feel like I'm pretending to be a functional adult","intent": "self_esteem"},
    {"text": "I feel like a disappointment to everyone including myself",   "intent": "self_esteem"},
    {"text": "I have deep shame about who I am",                            "intent": "self_esteem"},
    {"text": "I feel like other people are the real version of adults and I'm just playing pretend","intent": "self_esteem"},
    {"text": "I constantly apologise for taking up space",                  "intent": "self_esteem"},
    {"text": "I feel ugly inside and out",                                  "intent": "self_esteem"},
    {"text": "I believe people tolerate me rather than actually like me",   "intent": "self_esteem"},
    {"text": "I feel like I have nothing interesting to offer",             "intent": "self_esteem"},
    {"text": "I shrink myself so others feel more comfortable",             "intent": "self_esteem"},
    {"text": "I feel like my voice doesn't matter",                         "intent": "self_esteem"},
    {"text": "I'm terrified people will see through me and be disappointed","intent": "self_esteem"},
    {"text": "I feel like I don't deserve good things",                     "intent": "self_esteem"},
    {"text": "I compare myself to others on social media and feel terrible","intent": "self_esteem"},
    {"text": "I feel like I'm the least successful person I know",          "intent": "self_esteem"},
    {"text": "I've never felt proud of myself",                             "intent": "self_esteem"},
    {"text": "I feel too broken to be in a relationship",                   "intent": "self_esteem"},
    {"text": "I'm deeply insecure about my appearance",                     "intent": "self_esteem"},
    {"text": "I always feel like the odd one out",                          "intent": "self_esteem"},
    {"text": "I feel like I don't have a personality worth knowing",        "intent": "self_esteem"},

    # ── trauma ──────────────────────────────────────────────────────────────
    {"text": "Something happened to me as a child I've never talked about", "intent": "trauma"},
    {"text": "I keep having flashbacks from what happened",                 "intent": "trauma"},
    {"text": "I was abused and I still can't get past it",                  "intent": "trauma"},
    {"text": "I have nightmares about what happened",                       "intent": "trauma"},
    {"text": "Certain things trigger memories I'd rather forget",           "intent": "trauma"},
    {"text": "I feel unsafe even when there's no real danger",              "intent": "trauma"},
    {"text": "My body freezes when I'm reminded of the past",               "intent": "trauma"},
    {"text": "I've never told anyone what really happened",                 "intent": "trauma"},
    {"text": "I still feel shame about something that was done to me",      "intent": "trauma"},
    {"text": "I can't talk about it without breaking down",                 "intent": "trauma"},
    {"text": "The past keeps coming back even when I try to forget",        "intent": "trauma"},
    {"text": "I was assaulted and I still don't feel safe",                 "intent": "trauma"},
    {"text": "I've been carrying this secret for years",                    "intent": "trauma"},
    {"text": "I startle at loud noises ever since it happened",             "intent": "trauma"},
    {"text": "I feel dirty because of what was done to me",                 "intent": "trauma"},
    {"text": "I dissociate sometimes when things remind me of it",          "intent": "trauma"},
    {"text": "I was in a really bad accident and I'm not over it",          "intent": "trauma"},
    {"text": "Certain smells take me right back to what happened",          "intent": "trauma"},
    {"text": "I've been diagnosed with PTSD",                               "intent": "trauma"},
    {"text": "My childhood was not safe",                                   "intent": "trauma"},
    {"text": "I was emotionally abused for years",                          "intent": "trauma"},
    {"text": "I blame myself for what happened",                            "intent": "trauma"},
    {"text": "I never feel fully present because of the past",              "intent": "trauma"},
    {"text": "I saw something terrible that I can't unsee",                 "intent": "trauma"},
    {"text": "I have PTSD from my relationship",                            "intent": "trauma"},
    {"text": "There is something I experienced that I have never spoken about","intent": "trauma"},
    {"text": "I relive what happened over and over and I can't make it stop","intent": "trauma"},
    {"text": "I feel like the trauma has rewired my brain",                 "intent": "trauma"},
    {"text": "I feel permanently on high alert because of what I went through","intent": "trauma"},
    {"text": "Being touched unexpectedly makes me panic because of what happened","intent": "trauma"},
    {"text": "I felt powerless back then and I still do",                   "intent": "trauma"},
    {"text": "I've been through something I don't have words for",          "intent": "trauma"},
    {"text": "My past trauma affects every relationship I have",            "intent": "trauma"},
    {"text": "I grew up in a violent household and it still affects me",    "intent": "trauma"},
    {"text": "I flinch at things most people don't even notice",            "intent": "trauma"},
    {"text": "I feel like my childhood was stolen from me",                 "intent": "trauma"},
    {"text": "I was neglected as a child and I carry that with me",         "intent": "trauma"},
    {"text": "I've been having intrusive memories of a bad experience",     "intent": "trauma"},
    {"text": "I feel like something fundamental broke inside me back then", "intent": "trauma"},
    {"text": "I've never processed what happened to me",                    "intent": "trauma"},
    {"text": "The trauma responses catch me off guard when I least expect them","intent": "trauma"},
    {"text": "I was bullied so badly it changed who I am",                  "intent": "trauma"},
    {"text": "I was witness to something horrific and I can't shake it",    "intent": "trauma"},
    {"text": "I freeze when someone raises their voice because of my past", "intent": "trauma"},
    {"text": "The abuse left scars I can't see but can always feel",        "intent": "trauma"},
    {"text": "I feel like I'm still stuck in the moment it happened",       "intent": "trauma"},
    {"text": "I was in a toxic relationship that left me damaged",          "intent": "trauma"},
    {"text": "I've been running from something that happened to me",        "intent": "trauma"},
    {"text": "What happened to me as a teenager still haunts me",           "intent": "trauma"},
    {"text": "I feel like damaged goods because of my past",                "intent": "trauma"},

    # ── gratitude ───────────────────────────────────────────────────────────
    {"text": "Talking to you really helped me last time",                   "intent": "gratitude"},
    {"text": "Thank you I feel so much better",                             "intent": "gratitude"},
    {"text": "I really appreciate you listening",                           "intent": "gratitude"},
    {"text": "This has been so helpful thank you",                          "intent": "gratitude"},
    {"text": "I feel heard and that means a lot",                           "intent": "gratitude"},
    {"text": "You really helped me see things differently",                 "intent": "gratitude"},
    {"text": "I'm grateful for this space to talk",                         "intent": "gratitude"},
    {"text": "I feel lighter after talking to you",                         "intent": "gratitude"},
    {"text": "Thank you for not judging me",                                "intent": "gratitude"},
    {"text": "That really resonated with me thank you",                     "intent": "gratitude"},
    {"text": "I feel less alone now",                                       "intent": "gratitude"},
    {"text": "I appreciate that you remembered what I shared",              "intent": "gratitude"},
    {"text": "Your question made me think thank you",                       "intent": "gratitude"},
    {"text": "I needed to hear that so much",                               "intent": "gratitude"},
    {"text": "This is exactly what I needed today",                         "intent": "gratitude"},
    {"text": "Thank you for being patient with me",                         "intent": "gratitude"},
    {"text": "I feel validated and that helps more than you know",          "intent": "gratitude"},
    {"text": "I'm glad I came back to talk today",                          "intent": "gratitude"},
    {"text": "Last session really changed my perspective",                  "intent": "gratitude"},
    {"text": "I feel more hopeful after talking",                           "intent": "gratitude"},
    {"text": "You help me understand myself better",                        "intent": "gratitude"},
    {"text": "I'm grateful you don't give up on me",                        "intent": "gratitude"},
    {"text": "Thank you for everything",                                    "intent": "gratitude"},
    {"text": "I feel safe talking to you",                                  "intent": "gratitude"},
    {"text": "This place has become really important to me",                "intent": "gratitude"},
    {"text": "I just wanted to say thank you for being here",               "intent": "gratitude"},
    {"text": "Talking here is the one thing that helps me feel okay",       "intent": "gratitude"},
    {"text": "I feel understood and that is rare for me",                   "intent": "gratitude"},
    {"text": "Coming here was the best decision I made",                    "intent": "gratitude"},
    {"text": "You helped me get through a really dark time",                "intent": "gratitude"},
    {"text": "I'm so grateful this space exists",                           "intent": "gratitude"},
    {"text": "I feel like I can breathe again after talking",               "intent": "gratitude"},
    {"text": "I never feel judged here and that matters so much",           "intent": "gratitude"},
    {"text": "Thank you for helping me through that",                       "intent": "gratitude"},
    {"text": "I feel genuinely cared for when I talk here",                 "intent": "gratitude"},
    {"text": "That question unlocked something for me thank you",           "intent": "gratitude"},
    {"text": "I'm grateful you take what I say seriously",                  "intent": "gratitude"},
    {"text": "Talking to you helps more than I can put into words",         "intent": "gratitude"},
    {"text": "I wanted to come back and say that last time helped enormously","intent": "gratitude"},
    {"text": "This is the only place I feel truly heard",                   "intent": "gratitude"},
    {"text": "I feel so much better than when I arrived",                   "intent": "gratitude"},
    {"text": "Thank you for remembering the things I shared before",        "intent": "gratitude"},
    {"text": "I feel hopeful because of our conversations",                 "intent": "gratitude"},
    {"text": "I just wanted to thank you before I go",                      "intent": "gratitude"},
    {"text": "That really helped me shift my thinking",                     "intent": "gratitude"},
    {"text": "I feel lighter than I have in a long time",                   "intent": "gratitude"},
    {"text": "I appreciate how you hold space for me",                      "intent": "gratitude"},
    {"text": "Coming back here felt like coming home",                      "intent": "gratitude"},
    {"text": "I feel a kind of peace after talking to you",                 "intent": "gratitude"},
    {"text": "You always know the right questions to ask thank you",        "intent": "gratitude"},

    # ── progress ────────────────────────────────────────────────────────────
    {"text": "I actually had a good week for once",                         "intent": "progress"},
    {"text": "I stood up for myself today and it felt amazing",             "intent": "progress"},
    {"text": "I've been sleeping better lately",                            "intent": "progress"},
    {"text": "I went outside today for the first time in a while",          "intent": "progress"},
    {"text": "I said no to someone and didn't feel guilty",                 "intent": "progress"},
    {"text": "I finished something I'd been putting off",                   "intent": "progress"},
    {"text": "I feel like I'm making real progress",                        "intent": "progress"},
    {"text": "I talked to my mum and it actually went well",                "intent": "progress"},
    {"text": "I managed my anxiety without spiralling",                     "intent": "progress"},
    {"text": "I've been journalling and it's helping",                      "intent": "progress"},
    {"text": "I ate three proper meals today",                              "intent": "progress"},
    {"text": "I stopped a negative thought before it spiralled",            "intent": "progress"},
    {"text": "I reached out to a friend instead of isolating",              "intent": "progress"},
    {"text": "I completed my assignment and feel proud",                    "intent": "progress"},
    {"text": "I had a moment of genuine happiness today",                   "intent": "progress"},
    {"text": "I feel stronger than I did last month",                       "intent": "progress"},
    {"text": "I finally started therapy",                                   "intent": "progress"},
    {"text": "I exercised for the first time in months",                    "intent": "progress"},
    {"text": "I talked about my feelings instead of bottling up",           "intent": "progress"},
    {"text": "I had a difficult conversation and handled it well",          "intent": "progress"},
    {"text": "I've been practising the things we talked about",             "intent": "progress"},
    {"text": "I'm starting to recognise my own patterns",                   "intent": "progress"},
    {"text": "I let myself feel proud today",                               "intent": "progress"},
    {"text": "I set a boundary with my family and held it",                 "intent": "progress"},
    {"text": "Today I felt like myself for the first time in ages",         "intent": "progress"},
    {"text": "I actually got out of bed before noon today and that's huge", "intent": "progress"},
    {"text": "I cooked a proper meal for myself and it felt good",          "intent": "progress"},
    {"text": "I caught myself spiralling and talked myself down",           "intent": "progress"},
    {"text": "I am handling things better than I used to",                  "intent": "progress"},
    {"text": "I called a friend instead of disappearing into isolation",    "intent": "progress"},
    {"text": "I actually enjoyed something today which hasn't happened in a while","intent": "progress"},
    {"text": "I'm noticing I'm less reactive than I used to be",            "intent": "progress"},
    {"text": "I'm starting to believe I can actually get better",           "intent": "progress"},
    {"text": "I felt a moment of real calm today",                          "intent": "progress"},
    {"text": "I wrote in my journal for the first time in weeks",           "intent": "progress"},
    {"text": "I went for a walk and it actually helped",                    "intent": "progress"},
    {"text": "I feel like I'm finally moving in the right direction",       "intent": "progress"},
    {"text": "I passed something I was scared I'd fail",                    "intent": "progress"},
    {"text": "I apologised to someone and it went better than I expected",  "intent": "progress"},
    {"text": "I've been meditating and it's starting to make a difference", "intent": "progress"},
    {"text": "I chose not to self-isolate even though I wanted to",         "intent": "progress"},
    {"text": "I feel proud of how I handled something today",               "intent": "progress"},
    {"text": "I got through the week without a major crash",                "intent": "progress"},
    {"text": "I'm getting better at not catastrophising",                   "intent": "progress"},
    {"text": "I slept a full night for the first time in weeks",            "intent": "progress"},
    {"text": "I remembered something you said and it helped me in the moment","intent": "progress"},
    {"text": "I faced something I'd been avoiding and I survived",          "intent": "progress"},
    {"text": "I made a small step forward and it actually feels like something","intent": "progress"},
    {"text": "I'm seeing small improvements every day",                     "intent": "progress"},
    {"text": "I feel more in control of my emotions than before",           "intent": "progress"},

    # ── checking_in ─────────────────────────────────────────────────────────
    {"text": "Hey just checking in",                                        "intent": "checking_in"},
    {"text": "Hi how are you",                                              "intent": "checking_in"},
    {"text": "Good morning",                                                "intent": "checking_in"},
    {"text": "I just wanted to say hello",                                  "intent": "checking_in"},
    {"text": "Hey it's me again",                                           "intent": "checking_in"},
    {"text": "Hello I'm back",                                              "intent": "checking_in"},
    {"text": "Just popping in",                                             "intent": "checking_in"},
    {"text": "Hi I haven't been on in a while",                             "intent": "checking_in"},
    {"text": "Good evening",                                                "intent": "checking_in"},
    {"text": "Hey I thought I'd check in today",                            "intent": "checking_in"},
    {"text": "Hello again",                                                 "intent": "checking_in"},
    {"text": "Just wanted to touch base",                                   "intent": "checking_in"},
    {"text": "Hi there",                                                    "intent": "checking_in"},
    {"text": "Hey",                                                         "intent": "checking_in"},
    {"text": "Good to be back",                                             "intent": "checking_in"},
    {"text": "I'm back",                                                    "intent": "checking_in"},
    {"text": "Hello just wanted to connect",                                "intent": "checking_in"},
    {"text": "Hey I've been meaning to come back",                          "intent": "checking_in"},
    {"text": "Good afternoon",                                              "intent": "checking_in"},
    {"text": "Hi just wanted to check in with you",                         "intent": "checking_in"},
    {"text": "Hey good to see you",                                         "intent": "checking_in"},
    {"text": "Hello how have you been",                                     "intent": "checking_in"},
    {"text": "Just saying hi",                                              "intent": "checking_in"},
    {"text": "Hey I'm here",                                                "intent": "checking_in"},
    {"text": "Hi just dropping by",                                         "intent": "checking_in"},
    {"text": "Hey I'm back again",                                          "intent": "checking_in"},
    {"text": "Hi I just wanted to pop in and say hello",                    "intent": "checking_in"},
    {"text": "Hiya",                                                        "intent": "checking_in"},
    {"text": "Good night just wanted to check in before bed",               "intent": "checking_in"},
    {"text": "Just wanted to see how this felt coming back",                "intent": "checking_in"},
    {"text": "Hey it's been a while",                                       "intent": "checking_in"},
    {"text": "Hi just a quick hello",                                       "intent": "checking_in"},
    {"text": "Morning just here to talk",                                   "intent": "checking_in"},
    {"text": "Hey I missed coming here",                                    "intent": "checking_in"},
    {"text": "Just hello",                                                  "intent": "checking_in"},
    {"text": "Hi checking in",                                              "intent": "checking_in"},
    {"text": "Hey wanted to stop by",                                       "intent": "checking_in"},
    {"text": "Heya just wanted to say hi",                                  "intent": "checking_in"},
    {"text": "Not much to say just wanted to be here",                      "intent": "checking_in"},
    {"text": "Hello I came back",                                           "intent": "checking_in"},
    {"text": "Hi there it's me",                                            "intent": "checking_in"},
    {"text": "Yo just checking in",                                         "intent": "checking_in"},
    {"text": "Hey just wanted to talk",                                     "intent": "checking_in"},
    {"text": "Just here",                                                   "intent": "checking_in"},
    {"text": "Hey can we chat",                                             "intent": "checking_in"},
    {"text": "Hi just felt like coming by today",                           "intent": "checking_in"},
    {"text": "Greetings",                                                   "intent": "checking_in"},
    {"text": "Hey haven't talked in a few days",                            "intent": "checking_in"},
    {"text": "Just dropping in to say hello",                               "intent": "checking_in"},
    {"text": "Hi I'm here",                                                 "intent": "checking_in"},

    # ── general ─────────────────────────────────────────────────────────────
    {"text": "I had a strange day",                                         "intent": "general"},
    {"text": "Not sure where to start",                                     "intent": "general"},
    {"text": "I've been thinking a lot lately",                             "intent": "general"},
    {"text": "Something feels off but I can't place it",                    "intent": "general"},
    {"text": "I don't really know how I'm feeling",                         "intent": "general"},
    {"text": "I just needed to talk to someone",                            "intent": "general"},
    {"text": "I'm not sure what's going on with me",                        "intent": "general"},
    {"text": "I feel strange today and I can't explain it",                 "intent": "general"},
    {"text": "I've been a bit all over the place recently",                 "intent": "general"},
    {"text": "I wanted to talk but I'm not sure about what",                "intent": "general"},
    {"text": "Something happened today that I can't explain",               "intent": "general"},
    {"text": "I don't know where my head's at",                             "intent": "general"},
    {"text": "I just felt like reaching out",                               "intent": "general"},
    {"text": "I haven't been myself lately",                                "intent": "general"},
    {"text": "Things have been complicated",                                "intent": "general"},
    {"text": "I've been a bit lost recently",                               "intent": "general"},
    {"text": "I'm not really sure how to describe what I feel",             "intent": "general"},
    {"text": "I just want to process out loud",                             "intent": "general"},
    {"text": "I feel like something has shifted but I don't know what",     "intent": "general"},
    {"text": "I needed some space to think and talk",                       "intent": "general"},
    {"text": "I'm kind of just drifting right now",                         "intent": "general"},
    {"text": "I feel somewhere between okay and not okay",                  "intent": "general"},
    {"text": "I'm in a weird headspace lately",                             "intent": "general"},
    {"text": "Things feel uncertain and I don't like it",                   "intent": "general"},
    {"text": "I just want to talk through some things",                     "intent": "general"},
    {"text": "I'm not sure how I feel but I wanted to be here",             "intent": "general"},
    {"text": "Something is weighing on me but I can't name it",             "intent": "general"},
    {"text": "I feel a bit flat today",                                     "intent": "general"},
    {"text": "I'm feeling a mix of things and need to untangle them",       "intent": "general"},
    {"text": "I don't know if this is normal or if I should be worried",    "intent": "general"},
    {"text": "Things at home are a bit tense but nothing major",            "intent": "general"},
    {"text": "I feel restless and I don't know why",                        "intent": "general"},
    {"text": "I've been feeling slightly off for a few days",               "intent": "general"},
    {"text": "I need to process some things",                               "intent": "general"},
    {"text": "I feel like something is missing but I can't say what",       "intent": "general"},
    {"text": "I feel out of sorts today",                                   "intent": "general"},
    {"text": "I keep starting to say things and stopping",                  "intent": "general"},
    {"text": "I'm not in crisis I just needed to be heard",                 "intent": "general"},
    {"text": "I feel unsettled without knowing exactly why",                "intent": "general"},
    {"text": "I'm just here to talk about life",                            "intent": "general"},
    {"text": "I feel like my emotions are muffled",                         "intent": "general"},
    {"text": "Something small happened today but it affected me more than it should","intent": "general"},
    {"text": "I feel a bit foggy and disconnected today",                   "intent": "general"},
    {"text": "I'm in a contemplative mood today",                           "intent": "general"},
    {"text": "I've been thinking about my life a lot",                      "intent": "general"},
    {"text": "I feel like I'm at a crossroads",                             "intent": "general"},
    {"text": "I'm just not sure about things",                              "intent": "general"},
    {"text": "I feel blurry today",                                         "intent": "general"},
    {"text": "I just have a lot of thoughts and nowhere to put them",       "intent": "general"},
    {"text": "I feel okay but something isn't right",                       "intent": "general"},
]


def _tokenize(text: str) -> list[str]:
    text = text.lower()
    text = re.sub(r"([^\w\s'])", r" \1 ", text)
    return text.split()


_PERSON  = {"mum","mom","dad","father","mother","brother","sister","friend","partner",
            "boyfriend","girlfriend","husband","wife","boss","colleague","teacher","flatmate",
            "parents","family","manager","therapist"}
_TOPIC   = {"work","job","career","office","exam","deadline","school","university","uni",
            "sleep","health","relationship","money","studies","dissertation","presentation",
            "commute","therapy","journalling","coursework"}
_ISSUE   = {"anxiety","depression","trauma","abuse","panic","hopeless","suicide","cutting",
            "self-harm","ptsd","burnout","flashbacks","nightmares","dissociate","stress",
            "loneliness","grief","shame","guilt"}
_MOOD    = {"anxious","sad","angry","happy","hopeless","numb","empty","overwhelmed",
            "exhausted","furious","pissed","grateful","better","scared","terrified",
            "devastated","frustrated","lonely","worthless","guilty","ashamed","proud",
            "dread","restless","flat","hollow","disconnected","lost","lighter","calm"}


def _tag(tokens: list[str]) -> list[str]:
    tags, prev = [], "O"
    for tok in tokens:
        t = tok.strip("'.,!?")
        if t in _PERSON:
            tag = "B-PERSON" if prev != "I-PERSON" else "I-PERSON"; prev = "I-PERSON"
        elif t in _TOPIC:
            tag = "B-TOPIC"  if prev != "I-TOPIC"  else "I-TOPIC";  prev = "I-TOPIC"
        elif t in _ISSUE:
            tag = "B-ISSUE"  if prev != "I-ISSUE"  else "I-ISSUE";  prev = "I-ISSUE"
        elif t in _MOOD:
            tag = "B-MOOD"   if prev != "I-MOOD"   else "I-MOOD";   prev = "I-MOOD"
        else:
            tag = "O"; prev = "O"
        tags.append(tag)
    return tags


def main():
    random.seed(42)
    out = Path("training/data")
    out.mkdir(parents=True, exist_ok=True)

    records = []
    for item in SEED_DATA:
        tokens = _tokenize(item["text"])
        records.append({
            "text":     item["text"],
            "intent":   item["intent"],
            "tokens":   tokens,
            "dst_tags": _tag(tokens),
        })

    random.shuffle(records)
    split = int(len(records) * 0.85)
    write = lambda p, d: Path(p).write_text("\n".join(json.dumps(r) for r in d))
    write(out / "multitask_train.jsonl", records[:split])
    write(out / "multitask_val.jsonl",   records[split:])

    from collections import Counter
    intents = Counter(r["intent"] for r in records)
    print(f"Total: {len(records)}  Train: {split}  Val: {len(records)-split}")
    print("Per class:", dict(sorted(intents.items())))


if __name__ == "__main__":
    main()
